function process_data(Set);
    f = figure('Visible','off',...
              'Position',[100,200,700,500],...
              'MenuBar','none',...
              'Name','data processing');

    %ui elements
    uipanel_filters = uipanel('Title', 'Filters',...
                              'Units', 'normalized',...
                              'Position', [.05, .80, .90, .15]);
    uipanel_processes = uipanel('Title', 'Processes',...
                              'Units', 'normalized',...
                              'Position', [.05, .1, .90, .65]);
    done_button = uicontrol('Style', 'pushbutton', 'String', 'Done',...
                            'Units', 'normalized',...
                            'Position', [.9, .025, .075, .05],...
                            'Callback',{@done_button_Callback});
    acc_max_x_checkbox = uicontrol('Style', 'checkbox',...
                                   'Parent', uipanel_processes,...
                                   'String', 'max acceleration x',...
                                   'Units', 'normalized',...
                                   'Position', [.05, .9, .3, .05],...
                                   'Callback', {@max_accx_Callback});
    acc_max_y_checkbox = uicontrol('Style', 'checkbox',...
                                   'Parent', uipanel_processes,...
                                   'String', 'max acceleration y',...
                                   'Units', 'normalized',...
                                   'Position', [.05, .8, .3, .05],...
                                   'Callback', {@max_accy_Callback});

    function done_button_Callback(source, eventdata)
    end

    function max_accx_Callback(source,eventdata)
    end

    function max_accy_Callback(source,eventdata)
    end

    set(f, 'Visible', 'on');
    
    collector = calculation_collector();
    proc = processor();
end
