nSets = size(data,1);

% find the max number of drops for each dataset
for j = 1:nSets;
   n_list(j) = size(data{1,j},1);
end
n = max(n_list);

load = cell(1,nSets);
xload = cell(1,nSets);
yload = cell(1,nSets);
zload = cell(1,nSets);
position = cell(1,nSets);

%in case # drops is different
max_load = nan(n,nSets);
max_vert_a = nan(n,nSets);
max_for_a = nan(n,nSets);
max_xload = nan(n,nSets);
max_yload = nan(n,nSets);
max_zload = nan(n,nSets);


for i = 1:nSets
    DropSet = data{1,i};
    
    if isempty(DropSet) ~= 1
        [ load{1,i},...
          xload{1,i},...
          yload{1,i},...
          zload{1,i},...
          position{1,i},...
          load_rate{1,i},...
          xload_rate{1,i},...
          yload_rate{1,i},...
          zload_rate{1,i},...
          max_load(1:size(DropSet,1),i),...
          max_vert_a(1:size(DropSet,1),i),...
          max_for_a(1:size(DropSet,1),i),...
          for_accel{1,i},...
          vert_accel{1,i},...
          side_accel{1,i}...
          max_xload(1:size(DropSet,1),i),...
          max_yload(1:size(DropSet,1),i),...
          max_zload(1:size(DropSet,1),i)...
            ] = process_data_3axes(DropSet);
        
        clear DropSet
    end
end

clear nSets n n_list