% Preallocate

z = size(data,2);

for j = 1:z; % This loop sets up to find the max number of drops for each track (or experimental set)
   n_list(j) = size(data{1,j},1);
end

n = max(n_list); % Use the max number of drops for the largest set to preallocate

%n = size(data{1,1},1); %sample repetitions

load = cell(1,z);
xload = cell(1,z);
yload = cell(1,z);
zload = cell(1,z);
position = cell(1,z);

%max_load_rate = nan(n,z);
max_load = nan(n,z);
max_vert_a = nan(n,z);
max_for_a = nan(n,z);
max_xload = nan(n,z);
max_yload = nan(n,z);
max_zload = nan(n,z);


for i = 1:size(data,2) % representing a track or experimental set, i.e. harrow, 14%, 10.16cm (see labels)

    DropSet = data{1,i};
    
    if isempty(DropSet) ~= 1
        [ load{1,i},...
          xload{1,i},...
          yload{1,i},...
          zload{1,i},...
          position{1,i},...
          load_rate{1,i},...
          xload_rate{1,i},...
          yload_rate{1,i},...
          zload_rate{1,i},...
          max_load(1:size(DropSet,1),i),...
          max_vert_a(1:size(DropSet,1),i),...
          max_for_a(1:size(DropSet,1),i),...
          for_accel{1,i},...
          vert_accel{1,i},...
          side_accel{1,i}...
          max_xload(1:size(DropSet,1),i),...
          max_yload(1:size(DropSet,1),i),...
          max_zload(1:size(DropSet,1),i)...
            ] = process_data_3axes(DropSet);
        
        clear DropSet
    end
end

clear depth i j z n n_list