function save_data(Set, collector)
    f = figure('Visible','off',...
              'Position',[100,100,500,200],...
              'MenuBar','none',...
              'Name','files selection');
    addpath('lib/resources/');

    uipanel_settings = uipanel('Title', 'Settings',...
                               'Units', 'normalized',...
                               'Position', [.05, .225, .90, .7]);
    save_button = uicontrol('Style', 'pushbutton',...
                            'String', 'Save',...
                            'Units', 'normalized',...
                            'Position', [.85, .035, .11, .125],...
                            'Callback',{@save_button_callback});
    filepath_button = uicontrol('Style', 'pushbutton',...
                                'Parent', uipanel_settings,...
                                'Units', 'normalized',...
                                'String', 'data location',...
                                'Position', [.025, .7, .22, .2],...
                                'Callback',{@filepath_callback});
    ignore_flagged = uicontrol('Style', 'checkbox',...
                               'Parent', uipanel_settings,...
                               'String', '   Ignore flagged drops',...
                               'Units', 'normalized',...
                               'Position', [.1, .45, .5, .2],...
                               'Callback',{@ignore_flagged_drops_callback});
    ignore_signals= uicontrol('Style', 'checkbox',...
                               'Parent', uipanel_settings,...
                               'String', '   Ignore flagged signals',...
                               'Units', 'normalized',...
                               'Position', [.1, .25, .5, .2],...
                               'Callback',{@ignore_flagged_signals_callback});
    function filepath_callback(source, eventdata)
        [file, path] = uiputfile()
        filepath = fullfile(path, file)
    end

    function save_button_callback(source, eventdata)
        dumper.dump(filepath);
        delete(get(source, 'parent'));
    end

    filepath = [];
    dumper = data_dumper();
    dumper.grab_data(collector)

    set(f, 'Visible', 'on');
end
