sample_rate: 0.0005
text_file_extension: '*.txt'

#column -> signal settings
#if not used -- 'none'

string_pot: 1
head_pot: 'none'
single_axis_load: 2
loady: 3
loadx: 4
loadz: 5
accy: 6
accz: 7
accx: 8
