function validate_data(Set)
    f = figure('Visible','off',...
              'Position',[100,100,700,600],...
              'MenuBar','none',...
              'Name','files selection');

    uipanel_drops = uipanel('Title', 'Drops',...
                            'Units', 'normalized',...
                            'Position', [.025, .025, .35, .95]);
    uipanel_controls = uipanel('Title', 'Controls',...
                               'Units', 'normalized',...
                               'Position', [.4, .075, .575, .9]);
    drop_list = uicontrol('Style', 'listbox',...
                        'Parent', uipanel_drops,...
                        'Units', 'normalized',...
                        'Position', [.025, .01, .95, .98],...
                        'Callback', {@droplist_Callback},...
                        'Max', 1, 'Min', 1);
    current_drop_description = uicontrol('Style', 'text',...
                               'Parent', uipanel_controls,...
                               'Units', 'normalized',...
                               'Position', [.025, .875, .23, .1],...
                               'String', 'Current Drop: ');
    current_drop_text = uicontrol('Style', 'text',...
                               'Parent', uipanel_controls,...
                               'Units', 'normalized',...
                               'Position', [.25, .875, .3, .1]);
    done_button = uicontrol('Style', 'pushbutton', 'String', 'Done',...
                            'Units', 'normalized',...
                            'Position', [.9, .015, .075, .05],...
                            'Callback',{@done_button_Callback});

    function droplist_Callback(source, eventdata)
        set(current_drop_text, 'String', drop_ids(get(drop_list, 'Value')))
        current_drop = Set.drops(get(drop_list, 'Value'))
    end

    drop_ids = Set.drop_ids();
    current_drop = Set.drops(1);
    set(drop_list, 'String', drop_ids(:), 'Value', 1);
    set(f, 'Visible', 'on');
    
end
