function validate_data
    f = figure('Visible','off',...
              'Position',[100,100,700,600],...
              'MenuBar','none',...
              'Name','files selection');

    uipanel_drops = uipanel('Title', 'Drops',...
                            'Units', 'normalized',...
                            'Position', [.025, .025, .35, .95]);
    uipanel_controls = uipanel('Title', 'Controls',...
                               'Units', 'normalized',...
                               'Position', [.4, .075, .575, .9]);
    drop_list = uicontrol('Style', 'listbox',...
                        'Parent', uipanel_drops,...
                        'Units', 'normalized',...
                        'Position', [.025, .01, .95, .98],...
                        'Enable', 'off',...
                        'Callback', {@droplist_Callback},...
                        'Max', 10, 'Min', 1);
    current_drop_description = uicontrol('Style', 'text',...
                               'Parent', uipanel_controls,...
                               'Units', 'normalized',...
                               'Position', [.025, .875, .3, .1],...
                               'String', 'Current Drop:');
    done_button = uicontrol('Style', 'pushbutton', 'String', 'Done',...
                            'Units', 'normalized',...
                            'Position', [.9, .015, .075, .05],...
                            'Callback',{@done_button_Callback});
    set(filelist, 'String', drops_ids, 'Value', 1);
    set(f, 'Visible', 'on');
    
end
